### ISSUE TITLE
Programmabsturz bei Klick auf "X" zum Beenden

### ISSUE THREAD

**Issue by stes** [stes/it4kids#44]
```
[1]    9730 segmentation fault (core dumped)  ./it4kids-editor
```

in ae903c253ba56d890d71daccd615969b575c8185

**Comment by AndGL** [comment]
Nicht reproduzierbar unter Windows :/

**Comment by stes** [comment]
Ich checke es nochmal auf Linux, ggf. wurde das ganze mittlerweile auch schon (unbewusst) behoben.

**Comment by stes** [comment]
Auch bei der aktuellen Version taucht der Fehler auf
