### ISSUE TITLE
Lastenheft und Roadmap bis Ende Februar

### ISSUE THREAD

**Issue by stes** [stes/it4kids#56]
## Geplante Releases

- 20. Januar: Alpha Preview Release cb23d2f7240fc1ffb42d397b525e9e8a88d3a7b3
    - Implementierung aller wesentlichen Funktionen zumindest als Klickdummy
- 31. Januar: Alpha Release *TODO*
    - Funktionale Implementierung aller Funktionen
- 28. Februar: Beta Release *TODO*

### GUI

- Implementierung aller optischen Features von Snap und Scratch
- Gamification Ansätze (*Skilltree*/Kompetenzenkarte in elektronisch)
- Lehrer/Schüler Funktionalität, Verteilung von Material über das lokale Netzwerk

### Codegenerierung
- Zwei Wege Synchronisierung von Blöcken zu/von Sourcecode
- Standalone Ausführung der Programme
- Zugang zum kompletten Python Code
- Kompatibilität zu Snap und Scratch

### Backend
- Cloudspeicherung aller Dateien und Libraries, die im Kursbetrieb verwendet werden
- Anlegen und Verwaltung von Kursen + Synchronisation
- Multiplayeransätze über lokales Netzwerk

**Comment by Redix** [comment]
Einzelne Issues anlegen
