### ISSUE TITLE
Python Backend: Alle nötigen C-Funktionen implementieren (z.B. um die Figuren vor Programmausführung zu verschieben o. ä.)

### ISSUE THREAD

**Issue by stes** [stes/it4kids#6]
Bitte hier kommentieren wie das ganze konkret gelöst werden soll

**Comment by Redix** [comment]
Nach aktuellem Stand soll nur der in Qt aufgenommene Input an Python weitergegeben werden. Der Rest (Figuren bewegen, etc.) wird direkt in Python umgesetzt.

**Comment by stes** [comment]
Dann mache ich mal zu.
