### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by Redix** [stes/it4kids#64]
Wenn ich beispielsweise folgenden Block entferne, wird das 'move' Feld weiterhin angezeigt und das Programm stürzt ab sobald ich das Feld anklicke.
![crash](https://cloud.githubusercontent.com/assets/550744/15201664/9ef79284-17f3-11e6-87a0-dfc822dbded6.PNG)

**Comment by AndGL** [comment]
Bug ist im GUI branch gefixxt 26e582ac8114e02d5d31ba591d74131dc798f448
